name: News Bot Auto Run

# 스케줄 설정: 하루 2번 (오전 9시, 오후 6시 - 한국시간)
# GitHub Actions는 UTC 기준이므로 -9시간 (한국시간 9시 = UTC 0시, 한국시간 18시 = UTC 9시)
on:
  schedule:
    - cron: '0 0 * * *'    # 매일 오전 9시 (한국시간)
    - cron: '0 9 * * *'    # 매일 오후 6시 (한국시간)
  
  # 수동 실행도 가능하게 설정
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Python 환경 설정
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # 3. 필요한 라이브러리 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser
    
    # 4. 뉴스봇 실행
    - name: Run News Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python news_bot.py
    
    # 5. 실행 결과 로그
    - name: Log completion
      run: echo "News bot completed at $(date)"
